$(document).ready(function(){$(".group1").colorbox({rel:'group1'});$(".group2").colorbox({rel:'group2',transition:"fade"});$(".group3").colorbox({rel:'group3',transition:"none",width:"75%",height:"75%"});$(".group4").colorbox({rel:'group4',slideshow:!0});$(".ajax").colorbox();$(".youtube").colorbox({iframe:!0,innerWidth:640,innerHeight:390});$(".vimeo").colorbox({iframe:!0,innerWidth:500,innerHeight:409});$(".iframe").colorbox({iframe:!0,width:"80%",height:"80%"});$(".inline").colorbox({inline:!0,width:"50%"});$(".callbacks").colorbox({onOpen:function(){alert('onOpen: colorbox is about to open')},onLoad:function(){alert('onLoad: colorbox has started to load the targeted content')},onComplete:function(){alert('onComplete: colorbox has displayed the loaded content')},onCleanup:function(){alert('onCleanup: colorbox has begun the close process')},onClosed:function(){alert('onClosed: colorbox has completely closed')}});$('.non-retina').colorbox({rel:'group5',transition:'none'})
$('.retina').colorbox({rel:'group5',transition:'none',retinaImage:!0,retinaUrl:!0});$("#click").click(function(){$('#click').css({"background-color":"#f00","color":"#fff","cursor":"inherit"}).text("Open this window again and this message will still be here.");return!1})});$(document).ready(function(){$('.btn-outline-m').click(function(){$(this).toggleClass('selected')})});$(document).ready(function(){$('.btn-outline-w').click(function(){$(this).toggleClass('selected')})});$(document).ready(function(){$('.btn-outline').click(function(){$(this).toggleClass('selected')})});$(window).scroll(function(){if($(".navbar").offset().top>50){$(".navbar-fixed-top").addClass("top-nav-collapse")}else{$(".navbar-fixed-top").removeClass("top-nav-collapse")}});$(window).scroll(function(){if($(".navbar").offset().top>50){$(".b-outline").addClass("b-collapse")}else{$(".b-outline").removeClass("b-collapse")}});(function($){jQuery.scrollSpeed=function(step,speed,easing){var $document=$(document),$window=$(window),$body=$('html, body'),option=easing||'default',root=0,scroll=!1,scrollY,scrollX,view;if(window.navigator.msPointerEnabled)
return!1;$window.on('mousewheel DOMMouseScroll',function(e){var deltaY=e.originalEvent.wheelDeltaY,detail=e.originalEvent.detail;scrollY=$document.height()>$window.height();scrollX=$document.width()>$window.width();scroll=!0;if(scrollY){view=$window.height();if(deltaY<0||detail>0)
root=(root+view)>=$document.height()?root:root+=step;if(deltaY>0||detail<0)
root=root<=0?0:root-=step;$body.stop().animate({scrollTop:root},speed,option,function(){scroll=!1})}
if(scrollX){view=$window.width();if(deltaY<0||detail>0)
root=(root+view)>=$document.width()?root:root+=step;if(deltaY>0||detail<0)
root=root<=0?0:root-=step;$body.stop().animate({scrollLeft:root},speed,option,function(){scroll=!1})}
return!1}).on('scroll',function(){if(scrollY&&!scroll)root=$window.scrollTop();if(scrollX&&!scroll)root=$window.scrollLeft()}).on('resize',function(){if(scrollY&&!scroll)view=$window.height();if(scrollX&&!scroll)view=$window.width()})};jQuery.easing.default=function(x,t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b}})(jQuery);$(function(){jQuery.scrollSpeed(150,1500)});$(window).scroll(function(){if($(".navbar").offset().top>50){$(".sc-top").addClass("visible")}else{$(".sc-top").removeClass("visible")}});$(document).ready(function(){$(".sc-top > a").click(function(){var scroll_elem=$(this).attr('href');if($(scroll_elem).length!=0){$('html, body').animate({scrollTop:$(scroll_elem).offset().top},500)}
return!1})})